package br.com.treinaweb.calculadora.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-04-27T18:52:45.182-03:00
 * Generated source version: 3.5.2
 *
 */
@WebService(targetNamespace = "http://ws.calculadora.treinaweb.com.br/", name = "CalculadoraWSEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface CalculadoraWSEndpoint {

	@WebMethod(action = "urn:Somar")
	@RequestWrapper(localName = "somar", targetNamespace = "http://ws.calculadora.treinaweb.com.br/", className = "br.com.treinaweb.calculadora.ws.Somar")
	@ResponseWrapper(localName = "somarResponse", targetNamespace = "http://ws.calculadora.treinaweb.com.br/", className = "br.com.treinaweb.calculadora.ws.SomarResponse")
	@WebResult(name = "return", targetNamespace = "")
	int somar(@WebParam(name = "arg0") int n1, @WebParam(name = "arg1") int n2);

}