
package br.com.treinaweb.calculadora.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.2
 * Tue Apr 26 18:33:27 BRT 2022
 * Generated source version: 3.5.2
 */

@XmlRootElement(name = "somarResponse", namespace = "http://ws.calculadora.treinaweb.com.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "somarResponse", namespace = "http://ws.calculadora.treinaweb.com.br/")

public class SomarResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

